# -*- coding: utf-8 -*-
"""Analisis 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_UvPM0LHjgzZ7Vx0f-LmZMYT4MGBR6-
"""

import pandas as pd
import re
from openpyxl import load_workbook
from openpyxl.styles import PatternFill
from openpyxl.chart import BarChart, Reference

def process_ppni_audit_visual(file_path, output_path):
    # 1. Membaca dan Membersihkan Data
    df_raw = pd.read_excel(file_path, header=None)
    raw_list = df_raw[1].dropna().tolist()

    field_rules = {
        'DPK': ['DPK'], 'NIRA': ['NIRA', 'Nira'], 'KTP': ['KTP'],
        'STR': ['STR'], 'Phone': ['NO HP'], 'Birth_Info': ['TTL'],
        'Address': ['ALAMAT'], 'Email': ['Email', 'EMAIL', '@']
    }

    records, current_record = [], {}
    for item in raw_list:
        item = str(item).strip()
        if re.match(r'^\d+\.$', item):
            if current_record: records.append(current_record)
            current_record = {'No': item.replace('.', '')}
            continue
        found_prefix = False
        for col_name, keywords in field_rules.items():
            for kw in keywords:
                if kw.upper() in item.upper():
                    current_record[col_name] = item.split(':', 1)[1].strip() if ':' in item else item.strip()
                    found_prefix = True
                    break
            if found_prefix: break
        if not found_prefix and 'No' in current_record and 'Name' not in current_record:
            current_record['Name'] = item

    if current_record: records.append(current_record)
    df_clean = pd.DataFrame(records)

    # 2. Analisis DPK & Kesehatan Data (Bulatkan Persentase)
    dpk_summary = df_clean['DPK'].value_counts().reset_index()
    dpk_summary.columns = ['Nama DPK', 'Jumlah Anggota']

    health_report = (1 - df_clean.isnull().mean()) * 100
    health_report = health_report.round(2).reset_index()
    health_report.columns = ['Nama Kolom', 'Persentase (%)']

    # 3. Simpan ke Excel awal
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        df_clean.to_excel(writer, sheet_name='Master_Data_Bersih', index=False)
        dpk_summary.to_excel(writer, sheet_name='Analisis_DPK', index=False)
        health_report.to_excel(writer, sheet_name='Audit_Kesehatan_Data', index=False)

    # 4. Tambahkan Pewarnaan & Grafik (Openpyxl)
    wb = load_workbook(output_path)
    ws_master = wb['Master_Data_Bersih']

    # Warna: Merah Muda (FF9999) & Kuning Muda (FFFF99) agar teks tetap terbaca
    red_fill = PatternFill(start_color="FF9999", end_color="FF9999", fill_type="solid")
    yellow_fill = PatternFill(start_color="FFFF99", end_color="FFFF99", fill_type="solid")

    # Warnai baris berdasarkan jumlah data kosong
    for r_idx, row in enumerate(df_clean.values, start=2):
        empty_count = pd.Series(row).isnull().sum()
        fill_to_apply = None

        if empty_count > 2:
            fill_to_apply = red_fill
        elif 1 <= empty_count <= 2:
            fill_to_apply = yellow_fill

        if fill_to_apply:
            for c_idx in range(1, len(df_clean.columns) + 1):
                ws_master.cell(row=r_idx, column=c_idx).fill = fill_to_apply

    # 5. Sheet Visualisasi (Grafik Batang)
    ws_viz = wb.create_sheet('Visualisasi_Data')

    # Grafik DPK
    chart_dpk = BarChart()
    chart_dpk.title = "Distribusi Anggota per DPK"
    chart_dpk.add_data(Reference(wb['Analisis_DPK'], min_col=2, min_row=1, max_row=wb['Analisis_DPK'].max_row), titles_from_data=True)
    chart_dpk.set_categories(Reference(wb['Analisis_DPK'], min_col=1, min_row=2, max_row=wb['Analisis_DPK'].max_row))
    ws_viz.add_chart(chart_dpk, "A2")

    # Grafik Kesehatan Data
    chart_health = BarChart()
    chart_health.title = "Audit Kelengkapan Data (%)"
    chart_health.add_data(Reference(wb['Audit_Kesehatan_Data'], min_col=2, min_row=1, max_row=wb['Audit_Kesehatan_Data'].max_row), titles_from_data=True)
    chart_health.set_categories(Reference(wb['Audit_Kesehatan_Data'], min_col=1, min_row=2, max_row=wb['Audit_Kesehatan_Data'].max_row))
    ws_viz.add_chart(chart_health, "A20")

    wb.save(output_path)
    return output_path

# Jalankan
process_ppni_audit_visual('transfer-ppni-2025.xls', 'PPNI_Final_Audit_Report.xlsx')